external-api:
  stops:
    scheme: "https"
    host: "data.cityofchicago.org"
    path: "/resource/8pix-ypme.json"
  arrival:
    scheme: "http"
    host: "lapi.transitchicago.com/api/1.0"
    path: "ttarrivals.aspx"
    key: "9d5f0f7eb96941a99a4eeaed221e3f1e"
    outputType: "JSON"

